server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/login_jdbc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
     minimum-idle: 5
     maximum-pool-size: 15
     auto-commit: true
     idle-timeout: 30000
     pool-name: DatebookHikariCP
     max-lifetime: 1800000
     connection-timeout: 10000
     connection-test-query: SELECT 1

